### ISSUE TITLE
Getting error no processes deployed with key 'loanApproval': processDefinition is null

### ISSUE THREAD

**Issue by plungu** [camunda/camunda-get-started-spring#1]
I'm trying to deploy the spring starter shared process engine branch (Bonus) to the Camunda server. I am getting an exception. Any idea how to solve this? I have followed the limited instructions in the tutorial.
https://docs.camunda.org/get-started/spring/shared-process-engine/

From the log I notice the Starter class is called but it does not seem to find the process key 'loanApproval'. Any help would be appreciated.

02-Feb-2017 11:22:29.549 SEVERE [localhost-startStop-9] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context: no processes deployed with key 'loanApproval': processDefinition is null
 org.camunda.bpm.engine.exception.NullValueException: no processes deployed with key 'loanApproval': processDefinition is null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.camunda.bpm.engine.impl.util.EnsureUtil.generateException(EnsureUtil.java:334)
	at org.camunda.bpm.engine.impl.util.EnsureUtil.ensureNotNull(EnsureUtil.java:49)
	at org.camunda.bpm.engine.impl.util.EnsureUtil.ensureNotNull(EnsureUtil.java:44)
	at org.camunda.bpm.engine.impl.persistence.deploy.DeploymentCache.findDeployedLatestProcessDefinitionByKey(DeploymentCache.java:134)
	at org.camunda.bpm.engine.impl.cmd.GetDeployedProcessDefinitionCmd.findByKey(GetDeployedProcessDefinitionCmd.java:84)
	at org.camunda.bpm.engine.impl.cmd.GetDeployedProcessDefinitionCmd.find(GetDeployedProcessDefinitionCmd.java:71)
	at org.camunda.bpm.engine.impl.cmd.GetDeployedProcessDefinitionCmd.execute(GetDeployedProcessDefinitionCmd.java:53)
	at org.camunda.bpm.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:43)
	at org.camunda.bpm.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:31)
	at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)
	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:104)
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:66)
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.camunda.bpm.engine.impl.ProcessInstantiationBuilderImpl.executeWithVariablesInReturn(ProcessInstantiationBuilderImpl.java:156)
	at org.camunda.bpm.engine.impl.ProcessInstantiationBuilderImpl.execute(ProcessInstantiationBuilderImpl.java:122)
	at org.camunda.bpm.engine.impl.ProcessInstantiationBuilderImpl.execute(ProcessInstantiationBuilderImpl.java:118)
	at org.camunda.bpm.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:73)
	at org.camunda.bpm.getstarted.loanapproval.Starter.afterPropertiesSet(Starter.java:26)

**Comment by meyerdan** [comment]
Hi plungu,

please ask this in the Forums: https://forum.camunda.org/
